# backend/compose-jenkins.test.yml
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: test-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: .
    container_name: test-backend
    ports:
      - "8090:8080"
    environment:
      - PORT=8080
      - DBURL=mysql
      - DBUSER=root
      - DBPASSWORD=password
      - DBDATABASE=todo
      - DBPORT=3306
    depends_on:
      mysql:
        condition: service_healthy
    command: npm start  # ✅ Start backend automatically
