# backend/compose-jenkins.test.yml
version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: test-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
    container_name: test-backend
    ports:
      - "8081:8080"
    environment:
      - TEST_MODE=true
      - PORT=8080
      - DBURL=test-mysql
      - DBUSER=root
      - DBPASSWORD=password
      - DBDATABASE=todo
      - DBPORT=3306
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "sleep 10 && npm start"  # ✅ Start backend automatically
