version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: test-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10  # ⬅️ Increased retries to ensure readiness

  backend:
    build:
      context: .
    container_name: test-backend
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - DBURL=test-mysql
      - DBUSER=root
      - DBPASSWORD=password
      - DBDATABASE=testdb
      - DBPORT=3306
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "sleep 15 && npm start"  # ⬅️ Waits extra time before starting

volumes:
  mysql_data:
