version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: test-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb  # Choose one!
      MYSQL_USER: root
    volumes:
      - mysql_data:/var/lib/mysql  # Persist MySQL data
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    container_name: test-backend
    restart: unless-stopped  # Ensures backend restarts if needed
    ports:
      - "8081:8080"
    environment:
      - PORT=8080
      - DBURL=test-mysql
      - DBUSER=root
      - DBPASSWORD=password
      - DBDATABASE=testdb  # Should match the MySQL service
      - DBPORT=3306
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "sleep 10 && npm start"  # Ensures MySQL is fully up

volumes:
  mysql_data:  # Persistent volume for MySQL
